version: "3.5"

services:

  #kafka
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: adidas-be-challenge-zookeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: adidas-be-challenge-kafka
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  schema-registry:
    image: confluentinc/cp-schema-registry:latest
    container_name: adidas-be-challenge-schema-registry
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper:2181
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: kafka:9092
      SCHEMA_REGISTRY_LISTENERS: http://schema-registry:8081
    depends_on:
      - kafka

  mysql:
    image: mysql:latest
    restart: always
    container_name: adidas-be-challenge-mysql
    environment:
      MYSQL_DATABASE: 'subscriptions'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      #      FIXME: exposed
      - '3306'
    command: --init-file /data/application/init.sql
    volumes:
      - mysql:/data/mysql
      - ./public-service/src/main/resources/init-subscriptions-db.sql:/data/application/init.sql

  public-service:
    image: localhost/adidas-be-challenge-publicservice:latest
    container_name: adidas-be-challenge-publicservice
    build:
      context: public-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    links:
      - "priority-sale-service"
    depends_on:
      - kafka

  priority-sale-service:
    image: localhost/adidas-be-challenge-prioritysaleservice:latest
    container_name: adidas-be-challenge-prioritysaleservice
    build:
      context: priority-sale-service
      dockerfile: Dockerfile
    ports:
      - "8180:8080"
    links:
      - "adi-club-service"
      - "email-service"
    depends_on:
      - kafka
      - mysql


  adi-club-service:
    image: localhost/adidas-be-challenge-adiclubservice:latest
    container_name: adidas-be-challenge-adiclubservice
    ports:
      - "8280:8080"
    build:
      context: adiclub-service
      dockerfile: Dockerfile
    depends_on:
      - kafka


  email-service:
    image: localhost/adidas-be-challenge-emailservice:latest
    container_name: adidas-be-challenge-emailservice
    build:
      context: email-service
      dockerfile: Dockerfile
    depends_on:
      - kafka

volumes:
  mysql: