kafka:
  bootstrapAddress: kafka:9092
  schemaRegistryAddress: http://schema-registry:8081
  topic:
    name: emails

mysql:
  driver: com.mysql.jdbc.Driver
  database:
    host: jdbc:mysql://mysql:3306/subscriptions
    user: user
    password: password

adi-club:
  serviceUrl: http://adi-club-service:8080
  path: /adiclub
  emailAddressParameter: ?emailAddress=


